
package com.mycompany.employemangment;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class Dashboard extends javax.swing.JFrame {

    private ArrayList<Department> departments;
    private ArrayList<Employee> employees;
    
    public Dashboard() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        SideMenuPanel = new javax.swing.JPanel();
        addDepartmentMenuPanel = new javax.swing.JPanel();
        addNewDepartmentMenuLabel1 = new javax.swing.JLabel();
        addEmployeeMenuPanel = new javax.swing.JPanel();
        addNewEmployeeMenuLabel = new javax.swing.JLabel();
        showEmployeeDetails = new javax.swing.JPanel();
        showEmployeeDetailsMenuLabel = new javax.swing.JLabel();
        userAccountMenuPanel = new javax.swing.JPanel();
        addUserAccountLabel = new javax.swing.JLabel();
        DashboardTitle = new javax.swing.JLabel();
        userAccountMenuPanel1 = new javax.swing.JPanel();
        LogoutLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        WelcomeBasePanel = new javax.swing.JPanel();
        WelcomePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addNewDeprtmentBasePanel = new javax.swing.JPanel();
        addnewDepartmentPanel = new javax.swing.JPanel();
        addNewDepartmentTitle = new javax.swing.JLabel();
        designationNameLabel = new javax.swing.JLabel();
        departmentNameLabel = new javax.swing.JLabel();
        departmentnameTextField = new javax.swing.JTextField();
        designationNameTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        addDepartmentButton = new javax.swing.JButton();
        addNewEmployeeBasePanel = new javax.swing.JPanel();
        addNewEmployeePanel = new javax.swing.JPanel();
        aaddNewEmployeeTitle = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        desigbnationLabel = new javax.swing.JLabel();
        lastnameLabel = new javax.swing.JLabel();
        departmentLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        designationComboBox = new javax.swing.JComboBox<>();
        departmentComboBox = new javax.swing.JComboBox<>();
        addEmployeeButton = new javax.swing.JButton();
        cancelButton1 = new javax.swing.JButton();
        showEmployeeDetailsBasePanel = new javax.swing.JPanel();
        showEmployeeDetailsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeDetailsTable = new javax.swing.JTable();
        AddUserAccountBasePanel = new javax.swing.JPanel();
        AddUserAccountPanel = new javax.swing.JPanel();
        AddUserAccountTitle = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jobTitleLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        retypePasswordLabell = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        jobTitleComboBox = new javax.swing.JComboBox<>();
        password1Field = new javax.swing.JPasswordField();
        password2Field = new javax.swing.JPasswordField();
        addUserButton = new javax.swing.JButton();
        cancelButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(914, 512));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        MainPanel.setMinimumSize(new java.awt.Dimension(914, 512));
        MainPanel.setPreferredSize(new java.awt.Dimension(1000, 600));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1002, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        MainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        SidePanel.setPreferredSize(new java.awt.Dimension(220, 600));

        SideMenuPanel.setBackground(new java.awt.Color(51, 0, 102));
        SideMenuPanel.setPreferredSize(new java.awt.Dimension(220, 600));

        addDepartmentMenuPanel.setBackground(new java.awt.Color(51, 0, 102));
        addDepartmentMenuPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addDepartmentMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDepartmentMenuPanelMouseClicked(evt);
            }
        });

        addNewDepartmentMenuLabel1.setBackground(new java.awt.Color(51, 0, 102));
        addNewDepartmentMenuLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        addNewDepartmentMenuLabel1.setForeground(new java.awt.Color(255, 255, 255));
        addNewDepartmentMenuLabel1.setText("Add New Department");
        addNewDepartmentMenuLabel1.setToolTipText("");
        addNewDepartmentMenuLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addNewDepartmentMenuLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNewDepartmentMenuLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addDepartmentMenuPanelLayout = new javax.swing.GroupLayout(addDepartmentMenuPanel);
        addDepartmentMenuPanel.setLayout(addDepartmentMenuPanelLayout);
        addDepartmentMenuPanelLayout.setHorizontalGroup(
            addDepartmentMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDepartmentMenuPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(addNewDepartmentMenuLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addDepartmentMenuPanelLayout.setVerticalGroup(
            addDepartmentMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDepartmentMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNewDepartmentMenuLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        addEmployeeMenuPanel.setBackground(new java.awt.Color(51, 0, 102));
        addEmployeeMenuPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addNewEmployeeMenuLabel.setBackground(new java.awt.Color(51, 0, 102));
        addNewEmployeeMenuLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        addNewEmployeeMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        addNewEmployeeMenuLabel.setText("Add New Employee");
        addNewEmployeeMenuLabel.setToolTipText("");
        addNewEmployeeMenuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addNewEmployeeMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNewEmployeeMenuLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addEmployeeMenuPanelLayout = new javax.swing.GroupLayout(addEmployeeMenuPanel);
        addEmployeeMenuPanel.setLayout(addEmployeeMenuPanelLayout);
        addEmployeeMenuPanelLayout.setHorizontalGroup(
            addEmployeeMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeeMenuPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(addNewEmployeeMenuLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addEmployeeMenuPanelLayout.setVerticalGroup(
            addEmployeeMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeeMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNewEmployeeMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        showEmployeeDetails.setBackground(new java.awt.Color(51, 0, 102));
        showEmployeeDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        showEmployeeDetailsMenuLabel.setBackground(new java.awt.Color(51, 0, 102));
        showEmployeeDetailsMenuLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        showEmployeeDetailsMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        showEmployeeDetailsMenuLabel.setText("Show Employee Details");
        showEmployeeDetailsMenuLabel.setToolTipText("");
        showEmployeeDetailsMenuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showEmployeeDetailsMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showEmployeeDetailsMenuLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout showEmployeeDetailsLayout = new javax.swing.GroupLayout(showEmployeeDetails);
        showEmployeeDetails.setLayout(showEmployeeDetailsLayout);
        showEmployeeDetailsLayout.setHorizontalGroup(
            showEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showEmployeeDetailsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(showEmployeeDetailsMenuLabel)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        showEmployeeDetailsLayout.setVerticalGroup(
            showEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showEmployeeDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showEmployeeDetailsMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        userAccountMenuPanel.setBackground(new java.awt.Color(51, 0, 102));
        userAccountMenuPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addUserAccountLabel.setBackground(new java.awt.Color(51, 0, 102));
        addUserAccountLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        addUserAccountLabel.setForeground(new java.awt.Color(255, 255, 255));
        addUserAccountLabel.setText("Add User Account");
        addUserAccountLabel.setToolTipText("");
        addUserAccountLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addUserAccountLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserAccountLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout userAccountMenuPanelLayout = new javax.swing.GroupLayout(userAccountMenuPanel);
        userAccountMenuPanel.setLayout(userAccountMenuPanelLayout);
        userAccountMenuPanelLayout.setHorizontalGroup(
            userAccountMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userAccountMenuPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(addUserAccountLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userAccountMenuPanelLayout.setVerticalGroup(
            userAccountMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userAccountMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addUserAccountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        DashboardTitle.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        DashboardTitle.setForeground(new java.awt.Color(255, 255, 255));
        DashboardTitle.setText("Dashboard");
        DashboardTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DashboardTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardTitleMouseClicked(evt);
            }
        });

        userAccountMenuPanel1.setBackground(new java.awt.Color(51, 0, 102));
        userAccountMenuPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LogoutLabel.setBackground(new java.awt.Color(51, 0, 102));
        LogoutLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        LogoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        LogoutLabel.setText("Logout");
        LogoutLabel.setToolTipText("");
        LogoutLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout userAccountMenuPanel1Layout = new javax.swing.GroupLayout(userAccountMenuPanel1);
        userAccountMenuPanel1.setLayout(userAccountMenuPanel1Layout);
        userAccountMenuPanel1Layout.setHorizontalGroup(
            userAccountMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userAccountMenuPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(LogoutLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userAccountMenuPanel1Layout.setVerticalGroup(
            userAccountMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userAccountMenuPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout SideMenuPanelLayout = new javax.swing.GroupLayout(SideMenuPanel);
        SideMenuPanel.setLayout(SideMenuPanelLayout);
        SideMenuPanelLayout.setHorizontalGroup(
            SideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addDepartmentMenuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addEmployeeMenuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(showEmployeeDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userAccountMenuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SideMenuPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(DashboardTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(userAccountMenuPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SideMenuPanelLayout.setVerticalGroup(
            SideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideMenuPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(DashboardTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(addDepartmentMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(addEmployeeMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(showEmployeeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(userAccountMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(userAccountMenuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidePanelLayout.createSequentialGroup()
                .addComponent(SideMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(SideMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Welcome Employee Managment Program");

        javax.swing.GroupLayout WelcomePanelLayout = new javax.swing.GroupLayout(WelcomePanel);
        WelcomePanel.setLayout(WelcomePanelLayout);
        WelcomePanelLayout.setHorizontalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomePanelLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        WelcomePanelLayout.setVerticalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout WelcomeBasePanelLayout = new javax.swing.GroupLayout(WelcomeBasePanel);
        WelcomeBasePanel.setLayout(WelcomeBasePanelLayout);
        WelcomeBasePanelLayout.setHorizontalGroup(
            WelcomeBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(WelcomeBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(WelcomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        WelcomeBasePanelLayout.setVerticalGroup(
            WelcomeBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
            .addGroup(WelcomeBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(WelcomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", WelcomeBasePanel);

        addNewDepartmentTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addNewDepartmentTitle.setText("Add New Department");

        designationNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        designationNameLabel.setText("Designation Name");

        departmentNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        departmentNameLabel.setText("Depratment Name");

        cancelButton.setBackground(new java.awt.Color(255, 0, 0));
        cancelButton.setText("Cancel");
        cancelButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        addDepartmentButton.setBackground(new java.awt.Color(0, 204, 0));
        addDepartmentButton.setText("Add Department");
        addDepartmentButton.setActionCommand("Add Department");
        addDepartmentButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addDepartmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDepartmentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addnewDepartmentPanelLayout = new javax.swing.GroupLayout(addnewDepartmentPanel);
        addnewDepartmentPanel.setLayout(addnewDepartmentPanelLayout);
        addnewDepartmentPanelLayout.setHorizontalGroup(
            addnewDepartmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addnewDepartmentPanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(addnewDepartmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addnewDepartmentPanelLayout.createSequentialGroup()
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(addDepartmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addnewDepartmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addNewDepartmentTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(addnewDepartmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(designationNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departmentNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(departmentnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(designationNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(239, 239, 239))
        );
        addnewDepartmentPanelLayout.setVerticalGroup(
            addnewDepartmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addnewDepartmentPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(addNewDepartmentTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(departmentNameLabel)
                .addGap(18, 18, 18)
                .addComponent(departmentnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(designationNameLabel)
                .addGap(18, 18, 18)
                .addComponent(designationNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(addnewDepartmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDepartmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addNewDeprtmentBasePanelLayout = new javax.swing.GroupLayout(addNewDeprtmentBasePanel);
        addNewDeprtmentBasePanel.setLayout(addNewDeprtmentBasePanelLayout);
        addNewDeprtmentBasePanelLayout.setHorizontalGroup(
            addNewDeprtmentBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addnewDepartmentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addNewDeprtmentBasePanelLayout.setVerticalGroup(
            addNewDeprtmentBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addnewDepartmentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", addNewDeprtmentBasePanel);

        aaddNewEmployeeTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        aaddNewEmployeeTitle.setText("Add New Employee");

        firstnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        firstnameLabel.setText("First Name");

        desigbnationLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        desigbnationLabel.setText("Designation");

        lastnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lastnameLabel.setText("Last Name");

        departmentLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        departmentLabel.setText("Department");

        phoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phoneNumberLabel.setText("Phone Number");

        addEmployeeButton.setBackground(new java.awt.Color(0, 204, 0));
        addEmployeeButton.setText("Add Employee");
        addEmployeeButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButtonActionPerformed(evt);
            }
        });

        cancelButton1.setBackground(new java.awt.Color(255, 0, 0));
        cancelButton1.setText("Cancel");
        cancelButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addNewEmployeePanelLayout = new javax.swing.GroupLayout(addNewEmployeePanel);
        addNewEmployeePanel.setLayout(addNewEmployeePanelLayout);
        addNewEmployeePanelLayout.setHorizontalGroup(
            addNewEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewEmployeePanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(addNewEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addNewEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(aaddNewEmployeeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(firstnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(addNewEmployeePanelLayout.createSequentialGroup()
                            .addComponent(departmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(69, 69, 69)
                            .addComponent(desigbnationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addNewEmployeePanelLayout.createSequentialGroup()
                        .addComponent(departmentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(69, 69, 69)
                        .addGroup(addNewEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addNewEmployeePanelLayout.createSequentialGroup()
                                .addComponent(cancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(addEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(designationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        addNewEmployeePanelLayout.setVerticalGroup(
            addNewEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewEmployeePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(aaddNewEmployeeTitle)
                .addGap(43, 43, 43)
                .addComponent(firstnameLabel)
                .addGap(18, 18, 18)
                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phoneNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(addNewEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmentLabel)
                    .addComponent(desigbnationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addNewEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(designationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(addNewEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addNewEmployeeBasePanelLayout = new javax.swing.GroupLayout(addNewEmployeeBasePanel);
        addNewEmployeeBasePanel.setLayout(addNewEmployeeBasePanelLayout);
        addNewEmployeeBasePanelLayout.setHorizontalGroup(
            addNewEmployeeBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(addNewEmployeeBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addNewEmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addNewEmployeeBasePanelLayout.setVerticalGroup(
            addNewEmployeeBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
            .addGroup(addNewEmployeeBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addNewEmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", addNewEmployeeBasePanel);

        employeeDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Phone Number", "Department Name", "Designation"
            }
        ));
        jScrollPane1.setViewportView(employeeDetailsTable);

        javax.swing.GroupLayout showEmployeeDetailsPanelLayout = new javax.swing.GroupLayout(showEmployeeDetailsPanel);
        showEmployeeDetailsPanel.setLayout(showEmployeeDetailsPanelLayout);
        showEmployeeDetailsPanelLayout.setHorizontalGroup(
            showEmployeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showEmployeeDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
        );
        showEmployeeDetailsPanelLayout.setVerticalGroup(
            showEmployeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showEmployeeDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout showEmployeeDetailsBasePanelLayout = new javax.swing.GroupLayout(showEmployeeDetailsBasePanel);
        showEmployeeDetailsBasePanel.setLayout(showEmployeeDetailsBasePanelLayout);
        showEmployeeDetailsBasePanelLayout.setHorizontalGroup(
            showEmployeeDetailsBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(showEmployeeDetailsBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(showEmployeeDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        showEmployeeDetailsBasePanelLayout.setVerticalGroup(
            showEmployeeDetailsBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
            .addGroup(showEmployeeDetailsBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showEmployeeDetailsBasePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(showEmployeeDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("tab3", showEmployeeDetailsBasePanel);

        AddUserAccountTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AddUserAccountTitle.setText("Add User Account");

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameLabel.setText("Username");

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameLabel.setText("Name");

        jobTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jobTitleLabel.setText("JobTitle");

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwordLabel.setText("Password");

        retypePasswordLabell.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        retypePasswordLabell.setText("Re-Type Password");

        jobTitleComboBox.setEditable(true);
        jobTitleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "HR MANAGER HR ASSISTANCE" }));

        addUserButton.setBackground(new java.awt.Color(0, 204, 0));
        addUserButton.setText("Add User");
        addUserButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        cancelButton2.setBackground(new java.awt.Color(255, 0, 0));
        cancelButton2.setText("Cancel");
        cancelButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cancelButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddUserAccountPanelLayout = new javax.swing.GroupLayout(AddUserAccountPanel);
        AddUserAccountPanel.setLayout(AddUserAccountPanelLayout);
        AddUserAccountPanelLayout.setHorizontalGroup(
            AddUserAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddUserAccountPanelLayout.createSequentialGroup()
                .addGroup(AddUserAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddUserAccountPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddUserAccountPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(AddUserAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jobTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddUserAccountTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jobTitleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddUserAccountPanelLayout.createSequentialGroup()
                                .addGroup(AddUserAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(AddUserAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(password1Field, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)))
                                .addGap(37, 37, 37)
                                .addGroup(AddUserAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password2Field, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                                    .addComponent(retypePasswordLabell, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(59, 59, 59))
        );
        AddUserAccountPanelLayout.setVerticalGroup(
            AddUserAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddUserAccountPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(AddUserAccountTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jobTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jobTitleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddUserAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(retypePasswordLabell))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddUserAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(AddUserAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AddUserAccountBasePanelLayout = new javax.swing.GroupLayout(AddUserAccountBasePanel);
        AddUserAccountBasePanel.setLayout(AddUserAccountBasePanelLayout);
        AddUserAccountBasePanelLayout.setHorizontalGroup(
            AddUserAccountBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddUserAccountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AddUserAccountBasePanelLayout.setVerticalGroup(
            AddUserAccountBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddUserAccountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", AddUserAccountBasePanel);

        MainPanel.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 780, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    
   
    private void addDepartmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDepartmentButtonActionPerformed
        departments = new ArrayList<> ();
        String enteredDepartmentName = departmentnameTextField.getText();
        String enteredDesignationName = designationNameTextField.getText();
        Department newDepartment = new Department(enteredDepartmentName,enteredDesignationName);
        departments.add(newDepartment);
        departmentnameTextField.setText("");
        designationNameTextField.setText("");
        updateComboBoxes();
        JOptionPane.showMessageDialog(Dashboard.this, "Department Added Successfuly");
    }//GEN-LAST:event_addDepartmentButtonActionPerformed
    
    private void  updateComboBoxes(){
        for(Department department:departments){
            departmentComboBox.addItem(department.getDepartmentName());
            designationComboBox.addItem(department.getDesignation());
        }
    }
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
                departmentnameTextField.setText("");
                designationNameTextField.setText("");
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void addEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeButtonActionPerformed
        employees = new ArrayList<>();
        String enteredEmployeeFirstName =firstNameTextField.getText();
        String enteredEmployeeLastname = lastNameTextField.getText();
        String employeeTelephoneNumber = phoneNumberTextField.getText();
        String selectedDepartmentName =(String) departmentComboBox.getSelectedItem();
        String selecteddesignationName = (String) designationComboBox.getSelectedItem();
        Employee newemployee = new Employee(enteredEmployeeFirstName,enteredEmployeeLastname,selectedDepartmentName,selecteddesignationName,employeeTelephoneNumber);
        employees.add(newemployee);
        DefaultTableModel model = (DefaultTableModel) employeeDetailsTable.getModel();
        Object[] rowData = new Object[5];
        rowData[0] = newemployee.getEmployeeFirstName();
        rowData[1] = newemployee.getEmployeeLastName();
        rowData[2] = newemployee.getEmployeePhoneNumber();
        rowData[3] = newemployee.getDepartmentName();
        rowData[4] = newemployee.getDesignation();
        model.addRow(rowData);
        firstNameTextField.setText("");
        lastNameTextField.setText("");
        phoneNumberTextField.setText("");
        JOptionPane.showMessageDialog(Dashboard.this, "Employee Added Successfuly");
    }//GEN-LAST:event_addEmployeeButtonActionPerformed

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton1ActionPerformed
        firstNameTextField.setText("");
        lastNameTextField.setText("");
        lastNameTextField.setText("");
    }//GEN-LAST:event_cancelButton1ActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        String enteredUsername = usernameField.getText();
        String enteredName = nameField.getText();
        String selectedJobTitle = (String) jobTitleComboBox.getSelectedItem();
        char[] password1Chars =password1Field.getPassword();
        char[] password2Chars = password2Field.getPassword();
        String enteredPassword1 = new String(password1Chars);
        String enteredPassword2 = new String(password2Chars);
        if(enteredPassword1.equals(enteredPassword2)){
            Login loginClassInstance = Login.getInstance();
            
            ArrayList<User> retrievedUserList = loginClassInstance.getusers();
            User newUser = new User(enteredName,enteredUsername,enteredPassword1,selectedJobTitle);
            retrievedUserList.add(newUser);
            usernameField.setText("");
            nameField.setText("");
            password1Field.setText("");
            password2Field.setText("");
            JOptionPane.showMessageDialog(Dashboard.this, "User Added Successfully");
            setVisible(false);
        }else{
        JOptionPane.showMessageDialog(Dashboard.this, "Password Mismatch");
        }
        
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void cancelButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton2ActionPerformed
            usernameField.setText("");
            nameField.setText("");
            password1Field.setText("");
            password2Field.setText("");
    }//GEN-LAST:event_cancelButton2ActionPerformed
    public void processList(Login login){
    ArrayList<User> users = login.getusers();
    }
    private void addDepartmentMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDepartmentMenuPanelMouseClicked
        checkUser(1);
    }//GEN-LAST:event_addDepartmentMenuPanelMouseClicked

    private void addNewEmployeeMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewEmployeeMenuLabelMouseClicked
        checkUser(2);
    }//GEN-LAST:event_addNewEmployeeMenuLabelMouseClicked

    private void showEmployeeDetailsMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showEmployeeDetailsMenuLabelMouseClicked
       checkUser(3);
    }//GEN-LAST:event_showEmployeeDetailsMenuLabelMouseClicked

    private void addUserAccountLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserAccountLabelMouseClicked

        User selectedUser=Login.getLoggedInUser();
        if(selectedUser!=null){
        boolean isAdmin ="ADMIN".equals(selectedUser.getJobTitle());
        if(isAdmin){
            jTabbedPane1.setEnabled(isAdmin);
            jTabbedPane1.setSelectedIndex(4);
            
        }
        }
        
    }//GEN-LAST:event_addUserAccountLabelMouseClicked
    private void checkUser(int index){
        User selectedUser = Login.getLoggedInUser();
        if(selectedUser!= null){
        boolean isAdmin = "ADMIN".equals(selectedUser.getJobTitle());
        if(isAdmin){
            jTabbedPane1.setEnabledAt(index, false);
            JOptionPane.showMessageDialog(jTabbedPane1, "Tab is locked for Admin");
            
        }else{
            jTabbedPane1.setSelectedIndex(index);
        }
        }
    }
    
    private void DashboardTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardTitleMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_DashboardTitleMouseClicked

    private void addNewDepartmentMenuLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewDepartmentMenuLabel1MouseClicked
        checkUser(1);
    }//GEN-LAST:event_addNewDepartmentMenuLabel1MouseClicked

    private void LogoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLabelMouseClicked
        setVisible(false);
        Login loginform = new Login();
        loginform.setVisible(true); 
    }//GEN-LAST:event_LogoutLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddUserAccountBasePanel;
    private javax.swing.JPanel AddUserAccountPanel;
    private javax.swing.JLabel AddUserAccountTitle;
    private javax.swing.JLabel DashboardTitle;
    private javax.swing.JLabel LogoutLabel;
    public javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SideMenuPanel;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JPanel WelcomeBasePanel;
    private javax.swing.JPanel WelcomePanel;
    private javax.swing.JLabel aaddNewEmployeeTitle;
    private javax.swing.JButton addDepartmentButton;
    private javax.swing.JPanel addDepartmentMenuPanel;
    private javax.swing.JButton addEmployeeButton;
    private javax.swing.JPanel addEmployeeMenuPanel;
    private javax.swing.JLabel addNewDepartmentMenuLabel1;
    private javax.swing.JLabel addNewDepartmentTitle;
    private javax.swing.JPanel addNewDeprtmentBasePanel;
    private javax.swing.JPanel addNewEmployeeBasePanel;
    private javax.swing.JLabel addNewEmployeeMenuLabel;
    private javax.swing.JPanel addNewEmployeePanel;
    private javax.swing.JLabel addUserAccountLabel;
    private javax.swing.JButton addUserButton;
    private javax.swing.JPanel addnewDepartmentPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JButton cancelButton2;
    private javax.swing.JComboBox<String> departmentComboBox;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JLabel departmentNameLabel;
    private javax.swing.JTextField departmentnameTextField;
    private javax.swing.JLabel desigbnationLabel;
    private javax.swing.JComboBox<String> designationComboBox;
    private javax.swing.JLabel designationNameLabel;
    private javax.swing.JTextField designationNameTextField;
    private javax.swing.JTable employeeDetailsTable;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jobTitleComboBox;
    private javax.swing.JLabel jobTitleLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField password1Field;
    private javax.swing.JPasswordField password2Field;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JLabel retypePasswordLabell;
    private javax.swing.JPanel showEmployeeDetails;
    private javax.swing.JPanel showEmployeeDetailsBasePanel;
    private javax.swing.JLabel showEmployeeDetailsMenuLabel;
    private javax.swing.JPanel showEmployeeDetailsPanel;
    private javax.swing.JPanel userAccountMenuPanel;
    private javax.swing.JPanel userAccountMenuPanel1;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
